name = "minigen"
version = "0.0.3"

[docs]
links = [
  { title = 'GitHub', href = 'https://github.com/mrdimosthenis/minigen' }
]

[repository]
type = "github"
user = "mrdimosthenis"
repo = "minigen"

[dependencies]
gleam_stdlib = "~> 0.21"

[dev-dependencies]
gleeunit = "~> 0.6"
