name = "minigen"
version = "0.1.0"

description = "Pure random data generation, appropriate for realistic simulations"
licences = ["Apache-2.0"]
repository = { type = "github", user = "mrdimosthenis", repo = "minigen" }
links = [{ title = 'GitHub', href = 'https://github.com/mrdimosthenis/minigen' }]

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
